"""M4 service contracts and executor adapters.

Importing this package is intentionally explicit about its database dependency;
the legacy CLI continues to import from :mod:`legal_rag` without touching it.
"""

from .run_executor import (
    CompletedHistoryMessage,
    DeterministicRunExecutor,
    ExecutionFailure,
    ExecutionTimeout,
    LegalChatRunExecutor,
    RunExecutionInput,
    RunExecutor,
    SafePayload,
    SafeRunResult,
    SafeStageCallback,
)
from .run_service import (
    ACTIVE_RUN_STATUSES,
    STAGE_EVENT_TYPES,
    TERMINAL_RUN_STATUSES,
    ActiveRunConflictError,
    FrozenRunInput,
    IdempotencyConflictError,
    InvalidRunStateError,
    LeaseLostError,
    MessagePage,
    MessageRecord,
    NotFoundError,
    Principal,
    ResourceNotFoundError,
    ResumeUnsupportedError,
    RunConfigurationUnavailableError,
    RunConflictError,
    RunEventRecord,
    RunRecord,
    RunResultRecord,
    RunService,
    RunServiceDataError,
    RunServiceError,
    ServiceContractError,
    ServicePrincipal,
    SessionInactiveError,
    SessionRecord,
    UnsafePayloadError,
    WorkerLeaseLostError,
    canonical_json_bytes,
    canonical_json_sha256,
)

__all__ = [
    "ACTIVE_RUN_STATUSES",
    "STAGE_EVENT_TYPES",
    "TERMINAL_RUN_STATUSES",
    "ActiveRunConflictError",
    "CompletedHistoryMessage",
    "DeterministicRunExecutor",
    "ExecutionFailure",
    "ExecutionTimeout",
    "FrozenRunInput",
    "IdempotencyConflictError",
    "InvalidRunStateError",
    "LeaseLostError",
    "LegalChatRunExecutor",
    "MessagePage",
    "MessageRecord",
    "NotFoundError",
    "Principal",
    "ResourceNotFoundError",
    "ResumeUnsupportedError",
    "RunConfigurationUnavailableError",
    "RunConflictError",
    "RunEventRecord",
    "RunExecutionInput",
    "RunExecutor",
    "RunRecord",
    "RunResultRecord",
    "RunService",
    "RunServiceDataError",
    "RunServiceError",
    "SafePayload",
    "SafeRunResult",
    "SafeStageCallback",
    "ServiceContractError",
    "ServicePrincipal",
    "SessionInactiveError",
    "SessionRecord",
    "UnsafePayloadError",
    "WorkerLeaseLostError",
    "canonical_json_bytes",
    "canonical_json_sha256",
]
