from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, replace
from math import sqrt
from pathlib import Path
from threading import Barrier
from typing import Any

import numpy as np
import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Engine, delete, func, insert, select, text, update
from sqlalchemy.exc import DBAPIError, IntegrityError

from legal_rag.chunking import article_chunks
from legal_rag.embeddings import (
    EMBEDDING_CACHE_SCHEMA_VERSION,
    EmbeddingCache,
    EmbeddingModelConfig,
    chunk_corpus_fingerprint,
    embedding_contract_fingerprint,
)
from legal_rag.models import LawArticle
from legal_rag.storage.ann import (
    AnnIndexError,
    AnnIndexUnsupportedError,
    AnnSearchPolicy,
    HnswIndexSpec,
    PostgresAnnRetrievalRepository,
    PostgresHnswIndexManager,
    _Explain,
)
from legal_rag.storage.contracts import LawVersionSpec, build_storage_import_bundle
from legal_rag.storage.migrations import alembic_config
from legal_rag.storage.repository import PostgresCorpusRepository
from legal_rag.storage.retrieval import (
    PostgresExactRetrievalRepository,
    RetrievalFilters,
)
from legal_rag.storage.schema import embedding_profile_generations, index_builds


@dataclass(frozen=True)
class _ArticleSpec:
    article_id: str
    article_number: str


def _unit_vector(inner_product: float, *, dimensions: int = 3) -> list[float]:
    if dimensions < 2:
        raise ValueError("fixture dimensions must be at least two")
    vector = [0.0] * dimensions
    vector[0] = inner_product
    vector[1] = sqrt(max(0.0, 1.0 - inner_product**2))
    return vector


def _build_bundle(
    *,
    prefix: str,
    scores: list[float],
    dimensions: int = 3,
    profile_suffix: str | None = None,
):
    specs = [
        _ArticleSpec(
            article_id=f"{prefix}-article-{index}",
            article_number=f"第{index}条",
        )
        for index in range(1, len(scores) + 1)
    ]
    articles = [
        LawArticle(
            article_id=spec.article_id,
            law_name=f"{prefix}测试法",
            article_number=spec.article_number,
            body=f"{spec.article_id} 正文。",
            raw_text=f"{spec.article_number} {spec.article_id} 正文。",
            source_file=f"fixtures/{prefix}.txt",
            line_no=index,
            parse_status="from_filename",
        )
        for index, spec in enumerate(specs, start=1)
    ]
    chunks = article_chunks(articles)
    resolved_suffix = profile_suffix or prefix
    revision = f"ann-revision-{resolved_suffix}"
    model = EmbeddingModelConfig(
        key=f"m3-ann-fixture-{resolved_suffix}",
        provider="fixture",
        model_name=f"fixture/ann-model-{resolved_suffix}",
        role="retrieval",
        revision=revision,
        normalize=True,
        dimensions=dimensions,
    )
    matrix = np.asarray(
        [_unit_vector(score, dimensions=dimensions) for score in scores],
        dtype=np.float32,
    )
    cache = EmbeddingCache(
        cache_dir=Path("fixture-cache"),
        chunk_ids=[chunk.chunk_id for chunk in chunks],
        vectors=matrix,
        metadata={
            "schema_version": EMBEDDING_CACHE_SCHEMA_VERSION,
            "chunk_count": len(chunks),
            "vector_count": len(chunks),
            "dimension": dimensions,
            "dtype": "float32",
            "chunk_strategy": chunks[0].strategy,
            "chunk_fingerprint": chunk_corpus_fingerprint(chunks),
            "embedding_key": model.key,
            "provider": model.provider,
            "model_name": model.model_name,
            "revision": model.revision,
            "normalize": model.normalize,
            "trust_remote_code": model.trust_remote_code,
            "query_prefix": model.query_prefix,
            "document_prefix": model.document_prefix,
            "embed_with_metadata": model.embed_with_metadata,
            "embedding_contract_fingerprint": embedding_contract_fingerprint(model),
        },
    )
    snapshot_id = f"snapshot-{prefix}-v1"
    bundle = build_storage_import_bundle(
        snapshot_id=snapshot_id,
        scope_id=f"scope-{prefix}",
        source_manifest={
            "schema_version": 1,
            "fixture": "m3-ann-retrieval",
            "prefix": prefix,
            "snapshot_id": snapshot_id,
        },
        laws=[
            LawVersionSpec(
                law_id=f"{prefix}-law",
                version_id=f"{prefix}-law-v1",
                title=f"{prefix}测试法",
                verification_status="verified",
                source_ref=f"fixtures/{prefix}.txt",
                valid_from="2024-01-01",
            )
        ],
        articles=articles,
        chunks=chunks,
        embedding_cache=cache,
        model_config=model,
        model_revision=revision,
        chunk_recipe={"strategy": chunks[0].strategy},
        article_version_ids={spec.article_id: f"{prefix}-law-v1" for spec in specs},
    )
    return bundle, specs


def _import_and_build(migrated_engine: Engine, *, prefix: str, scores: list[float]):
    bundle, specs = _build_bundle(prefix=prefix, scores=scores)
    PostgresCorpusRepository(migrated_engine).import_bundle(bundle)
    profile = bundle.embedding_profile.to_identity()
    filters = RetrievalFilters(
        scope_id=bundle.snapshot.scope_id,
        snapshot_id=bundle.snapshot.snapshot_id,
        profile_id=profile.profile_id,
    )
    build = PostgresHnswIndexManager(migrated_engine).ensure_index(
        filters=filters,
        expected_profile=profile,
    )
    return bundle, specs, profile, filters, build


def _index_metadata(engine: Engine, index_name: str) -> dict[str, Any]:
    with engine.connect() as connection:
        row = (
            connection.execute(
                text(
                    "SELECT i.indisvalid, i.indisready, am.amname, "
                    "pg_get_indexdef(i.indexrelid) AS indexdef, "
                    "pg_get_expr(i.indpred, i.indrelid) AS predicate "
                    "FROM pg_index AS i "
                    "JOIN pg_class AS idx ON idx.oid = i.indexrelid "
                    "JOIN pg_class AS tbl ON tbl.oid = i.indrelid "
                    "JOIN pg_namespace AS ns ON ns.oid = idx.relnamespace "
                    "JOIN pg_am AS am ON am.oid = idx.relam "
                    "WHERE ns.nspname = current_schema() "
                    "AND idx.relname = :index_name "
                    "AND tbl.relname = 'chunk_embeddings'"
                ),
                {"index_name": index_name},
            )
            .mappings()
            .one()
        )
    return dict(row)


def _collect_plan_index_names(value: Any) -> set[str]:
    if isinstance(value, dict):
        names = {
            str(value["Index Name"])
            for key in value
            if key == "Index Name" and isinstance(value[key], str)
        }
        for child in value.values():
            names.update(_collect_plan_index_names(child))
        return names
    if isinstance(value, list):
        names: set[str] = set()
        for child in value:
            names.update(_collect_plan_index_names(child))
        return names
    return set()


def _explain_ann_index_names(
    engine: Engine,
    *,
    profile_id: str,
    dimensions: int,
    snapshot_id: str,
    scope_id: str,
    query_vector: list[float],
    top_k: int,
) -> set[str]:
    repository = PostgresAnnRetrievalRepository(engine)
    statement = repository._search_statement(
        vector=query_vector,
        top_k=top_k,
        filters=RetrievalFilters(
            scope_id=scope_id,
            snapshot_id=snapshot_id,
            profile_id=profile_id,
        ),
        dimensions=dimensions,
    )
    with engine.begin() as connection:
        repository._set_query_policy(connection, AnnSearchPolicy())
        plan = connection.scalar(
            _Explain(statement),
        )
    return _collect_plan_index_names(plan)


def test_hnsw_partial_expression_index_is_real_idempotent_and_used(
    migrated_engine: Engine,
) -> None:
    bundle, _, profile, filters, build = _import_and_build(
        migrated_engine,
        prefix="ann-index-definition",
        scores=[0.99, 0.8, 0.5, 0.1, -0.2, -0.7],
    )
    repeated = PostgresHnswIndexManager(migrated_engine).ensure_index(
        filters=filters,
        expected_profile=profile,
    )

    assert build.reused is False
    assert repeated.reused is True
    assert repeated == replace(build, reused=True)
    with migrated_engine.connect() as connection:
        assert (
            connection.scalar(
                select(func.count())
                .select_from(index_builds)
                .where(index_builds.c.build_id == build.build_id)
            )
            == 1
        )

    metadata = _index_metadata(migrated_engine, build.physical_index_name)
    normalized_definition = " ".join(str(metadata["indexdef"]).lower().split())
    normalized_predicate = " ".join(str(metadata["predicate"]).lower().split())
    assert metadata["indisvalid"] is True
    assert metadata["indisready"] is True
    assert metadata["amname"] == "hnsw"
    assert "vector_ip_ops" in normalized_definition
    assert "vector(3)" in normalized_definition
    assert profile.profile_id in normalized_predicate
    assert "embedding_dimension" in normalized_predicate
    assert "3" in normalized_predicate

    used_indexes = _explain_ann_index_names(
        migrated_engine,
        profile_id=profile.profile_id,
        dimensions=profile.dimensions,
        snapshot_id=bundle.snapshot.snapshot_id,
        scope_id=bundle.snapshot.scope_id,
        query_vector=[1.0, 0.0, 0.0],
        top_k=3,
    )
    assert build.physical_index_name in used_indexes

    with migrated_engine.connect() as connection:
        command.check(alembic_config(connection=connection))

    rogue_name = "ix_ce_hnsw_ip_" + "f" * 32
    try:
        with migrated_engine.begin() as connection:
            connection.exec_driver_sql(
                f'CREATE INDEX "{rogue_name}" ON chunk_embeddings '
                "USING hnsw ((embedding::vector(3)) vector_ip_ops) "
                "WITH (m = 16, ef_construction = 64) "
                f"WHERE profile_id = '{profile.profile_id}' "
                "AND embedding_dimension = 999"
            )
        with migrated_engine.connect() as connection:
            with pytest.raises(AutogenerateDiffsDetected):
                command.check(alembic_config(connection=connection))
    finally:
        with migrated_engine.begin() as connection:
            connection.exec_driver_sql(f'DROP INDEX IF EXISTS "{rogue_name}"')


def test_same_dimension_profiles_have_isolated_indexes_and_results(
    migrated_engine: Engine,
) -> None:
    bundle_a, _, profile_a, filters_a, build_a = _import_and_build(
        migrated_engine,
        prefix="ann-profile-a",
        scores=[0.9, 0.2, -0.4],
    )
    bundle_b, _, profile_b, filters_b, build_b = _import_and_build(
        migrated_engine,
        prefix="ann-profile-b",
        scores=[0.8, 0.1, -0.5],
    )

    assert profile_a.dimensions == profile_b.dimensions == 3
    assert profile_a.profile_id != profile_b.profile_id
    assert build_a.physical_index_name != build_b.physical_index_name
    assert profile_a.profile_id in str(
        _index_metadata(migrated_engine, build_a.physical_index_name)["predicate"]
    )
    assert profile_b.profile_id in str(
        _index_metadata(migrated_engine, build_b.physical_index_name)["predicate"]
    )

    repository = PostgresAnnRetrievalRepository(migrated_engine)
    policy = AnnSearchPolicy(
        ef_search=100,
        max_scan_tuples=100_000,
        exact_fallback_on_underfill=False,
    )
    outcome_a = repository.search_vector(
        [1.0, 0.0, 0.0],
        top_k=1,
        filters=filters_a,
        expected_profile=profile_a,
        build=build_a,
        policy=policy,
    )
    outcome_b = repository.search_vector(
        [1.0, 0.0, 0.0],
        top_k=1,
        filters=filters_b,
        expected_profile=profile_b,
        build=build_b,
        policy=policy,
    )

    assert outcome_a.status == outcome_b.status == "ann_complete"
    assert outcome_a.results[0].chunk.chunk_id in {
        item.chunk_id for item in bundle_a.chunks
    }
    assert outcome_b.results[0].chunk.chunk_id in {
        item.chunk_id for item in bundle_b.chunks
    }
    assert outcome_a.results[0].provenance is not None
    assert outcome_b.results[0].provenance is not None
    assert outcome_a.results[0].provenance.profile_id == profile_a.profile_id
    assert outcome_b.results[0].provenance.profile_id == profile_b.profile_id
    assert outcome_a.results[0].provenance.snapshot_id == bundle_a.snapshot.snapshot_id
    assert outcome_b.results[0].provenance.snapshot_id == bundle_b.snapshot.snapshot_id


def test_concurrent_specs_create_one_physical_instance_and_one_conflict(
    migrated_engine: Engine,
) -> None:
    bundle, _ = _build_bundle(
        prefix="ann-concurrent-spec",
        scores=[0.9, 0.4, -0.2],
    )
    PostgresCorpusRepository(migrated_engine).import_bundle(bundle)
    profile = bundle.embedding_profile.to_identity()
    filters = RetrievalFilters(
        scope_id=bundle.snapshot.scope_id,
        snapshot_id=bundle.snapshot.snapshot_id,
        profile_id=profile.profile_id,
    )
    barrier = Barrier(2)

    def build(spec: HnswIndexSpec):
        barrier.wait(timeout=10)
        try:
            return PostgresHnswIndexManager(migrated_engine).ensure_index(
                filters=filters,
                expected_profile=profile,
                spec=spec,
            )
        except AnnIndexError as exc:
            return exc

    with ThreadPoolExecutor(max_workers=2) as executor:
        outcomes = list(
            executor.map(
                build,
                [HnswIndexSpec(), HnswIndexSpec(m=24, ef_construction=64)],
            )
        )

    successful = [item for item in outcomes if not isinstance(item, Exception)]
    conflicts = [item for item in outcomes if isinstance(item, AnnIndexError)]
    assert len(successful) == len(conflicts) == 1
    assert "different HNSW specification" in str(conflicts[0])
    winner = successful[0]
    with migrated_engine.connect() as connection:
        names = PostgresHnswIndexManager._matching_hnsw_index_names(
            connection,
            profile_id=profile.profile_id,
            dimensions=profile.dimensions,
        )
    assert names == {winner.physical_index_name}


def test_same_profile_import_invalidates_old_generation_receipt(
    migrated_engine: Engine,
) -> None:
    bundle_a, _ = _build_bundle(
        prefix="ann-generation-a",
        scores=[0.9, 0.5, 0.1],
        profile_suffix="shared-generation",
    )
    repository = PostgresCorpusRepository(migrated_engine)
    repository.import_bundle(bundle_a)
    profile = bundle_a.embedding_profile.to_identity()
    filters_a = RetrievalFilters(
        scope_id=bundle_a.snapshot.scope_id,
        snapshot_id=bundle_a.snapshot.snapshot_id,
        profile_id=profile.profile_id,
    )
    manager = PostgresHnswIndexManager(migrated_engine)
    first_build = manager.ensure_index(
        filters=filters_a,
        expected_profile=profile,
    )
    assert first_build.profile_embedding_count == 3

    bundle_b, _ = _build_bundle(
        prefix="ann-generation-b",
        scores=[0.8, 0.2],
        profile_suffix="shared-generation",
    )
    assert bundle_b.embedding_profile.profile_id == profile.profile_id
    repository.import_bundle(bundle_b)
    repository.import_bundle(bundle_b)

    ann_repository = PostgresAnnRetrievalRepository(migrated_engine)
    with pytest.raises(AnnIndexError, match="profile generation changed"):
        ann_repository.search_vector(
            [1.0, 0.0, 0.0],
            top_k=1,
            filters=filters_a,
            expected_profile=profile,
            build=first_build,
        )

    replacement = manager.ensure_index(
        filters=filters_a,
        expected_profile=profile,
    )
    assert replacement.profile_embedding_count == 5
    assert (
        replacement.profile_embedding_manifest_hash
        != first_build.profile_embedding_manifest_hash
    )
    assert replacement.physical_instance_id != first_build.physical_instance_id
    assert replacement.build_id != first_build.build_id
    assert replacement.physical_index_name != first_build.physical_index_name
    with migrated_engine.connect() as connection:
        assert (
            connection.scalar(
                text("SELECT to_regclass(:index_name)"),
                {"index_name": first_build.physical_index_name},
            )
            is None
        )
    outcome = ann_repository.search_vector(
        [1.0, 0.0, 0.0],
        top_k=1,
        filters=filters_a,
        expected_profile=profile,
        build=replacement,
    )
    assert len(outcome.results) == 1
    assert outcome.results[0].provenance is not None
    assert outcome.results[0].provenance.snapshot_id == bundle_a.snapshot.snapshot_id


def test_ann_matches_exact_for_the_same_boundary_and_distance(
    migrated_engine: Engine,
) -> None:
    scores = [0.99, 0.91, 0.82, 0.73, 0.64, 0.55, 0.46, 0.37, 0.28, 0.19]
    _, _, profile, filters, build = _import_and_build(
        migrated_engine,
        prefix="ann-exact-recall",
        scores=scores,
    )
    query = [1.0, 0.0, 0.0]
    top_k = 5
    exact = PostgresExactRetrievalRepository(migrated_engine).search_vector(
        query,
        top_k=top_k,
        filters=filters,
        expected_profile=profile,
    )
    outcome = PostgresAnnRetrievalRepository(migrated_engine).search_vector(
        query,
        top_k=top_k,
        filters=filters,
        expected_profile=profile,
        build=build,
        policy=AnnSearchPolicy(
            ef_search=200,
            max_scan_tuples=100_000,
            iterative_scan="strict_order",
            exact_fallback_on_underfill=False,
        ),
    )

    exact_ids = [item.chunk.chunk_id for item in exact]
    ann_ids = [item.chunk.chunk_id for item in outcome.results]
    assert outcome.status == "ann_complete"
    assert outcome.eligible_count is None
    assert ann_ids == exact_ids
    assert len(set(ann_ids) & set(exact_ids)) / top_k == 1.0
    np.testing.assert_allclose(
        [item.score for item in outcome.results],
        [item.score for item in exact],
        rtol=1e-5,
        atol=1e-6,
    )
    assert all(
        item.provenance is not None and filters.allows(item.provenance)
        for item in outcome.results
    )
    assert all(
        item.trace["ann_plan_verified"] is True
        and build.physical_index_name in item.trace["ann_plan_index_names"]
        and item.trace["ann_validated_physical_index_name"] == build.physical_index_name
        and "ann_physical_index_name" not in item.trace
        for item in outcome.results
    )


def test_filtered_underfill_is_typed_and_exact_fallback_is_boundary_preserving(
    migrated_engine: Engine,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    distractor_scores = [0.999 - index * 0.01 for index in range(24)]
    selected_scores = [-0.1, -0.2, -0.3, -0.4]
    _, specs, profile, base_filters, build = _import_and_build(
        migrated_engine,
        prefix="ann-filtered-underfill",
        scores=[*distractor_scores, *selected_scores],
    )
    selected_ids = tuple(spec.article_id for spec in specs[-4:])
    filters = replace(base_filters, article_ids=selected_ids)
    query = [1.0, 0.0, 0.0]
    repository = PostgresAnnRetrievalRepository(migrated_engine)
    constrained_policy = AnnSearchPolicy(
        ef_search=1,
        max_scan_tuples=1,
        iterative_scan="off",
        exact_fallback_on_underfill=False,
    )

    underfilled = repository.search_vector(
        query,
        top_k=3,
        filters=filters,
        expected_profile=profile,
        build=build,
        policy=constrained_policy,
    )

    assert underfilled.status == "ann_underfilled"
    assert underfilled.eligible_count is None
    assert underfilled.ann_returned_count < underfilled.requested_top_k
    assert underfilled.underfill_reason == "ann_underfill_unclassified"
    assert underfilled.exact_fallback_used is False
    assert all(
        item.provenance is not None
        and filters.allows(item.provenance)
        and all(
            article.article_id in selected_ids for article in item.provenance.articles
        )
        for item in underfilled.results
    )

    exact = PostgresExactRetrievalRepository(migrated_engine).search_vector(
        query,
        top_k=3,
        filters=filters,
        expected_profile=profile,
    )
    fallback = repository.search_vector(
        query,
        top_k=3,
        filters=filters,
        expected_profile=profile,
        build=build,
        policy=replace(constrained_policy, exact_fallback_on_underfill=True),
    )

    assert fallback.status == "exact_fallback_complete"
    assert fallback.exact_fallback_used is True
    assert fallback.eligible_count is None
    assert fallback.exact_returned_count == 3
    assert [item.chunk.chunk_id for item in fallback.results] == [
        item.chunk.chunk_id for item in exact
    ]
    assert all(
        item.retriever == "pgvector_hnsw_exact_fallback" for item in fallback.results
    )
    assert all(
        item.trace["search_mode"] == "exact_fallback"
        and item.trace["ann_outcome_status"] == "exact_fallback_complete"
        and item.provenance is not None
        and filters.allows(item.provenance)
        for item in fallback.results
    )
    with migrated_engine.connect() as connection:
        assert connection.scalar(text("SHOW statement_timeout")) == "0"

    one_article_filters = replace(base_filters, article_ids=(selected_ids[0],))
    exhausted_exact = PostgresExactRetrievalRepository(migrated_engine).search_vector(
        query,
        top_k=3,
        filters=one_article_filters,
        expected_profile=profile,
    )
    exhausted = repository.search_vector(
        query,
        top_k=3,
        filters=one_article_filters,
        expected_profile=profile,
        build=build,
        policy=replace(constrained_policy, exact_fallback_on_underfill=True),
    )

    assert exhausted.status == "exact_fallback_exhausted"
    assert exhausted.underfill_reason == "eligible_population_below_top_k"
    assert exhausted.eligible_count == 1
    assert exhausted.exact_returned_count == 1
    assert [item.chunk.chunk_id for item in exhausted.results] == [
        item.chunk.chunk_id for item in exhausted_exact
    ]

    class _StatementTimeout(Exception):
        sqlstate = "57014"

    def _timed_out_exact_fallback(*args, **kwargs):
        raise DBAPIError(
            "SELECT exact fallback",
            {},
            _StatementTimeout("statement timeout"),
            False,
        )

    monkeypatch.setattr(
        repository._exact,
        "search_vector",
        _timed_out_exact_fallback,
    )
    timed_out = repository.search_vector(
        query,
        top_k=3,
        filters=filters,
        expected_profile=profile,
        build=build,
        policy=replace(constrained_policy, exact_fallback_on_underfill=True),
    )
    assert timed_out.status == "exact_fallback_timed_out"
    assert timed_out.underfill_reason == "exact_fallback_statement_timeout"
    assert timed_out.eligible_count is None
    assert timed_out.exact_returned_count is None
    assert timed_out.exact_fallback_used is True


def test_ann_build_and_physical_index_drift_fail_closed(
    migrated_engine: Engine,
) -> None:
    _, _, profile, filters, build = _import_and_build(
        migrated_engine,
        prefix="ann-build-drift",
        scores=[0.9, 0.4, -0.2],
    )
    repository = PostgresAnnRetrievalRepository(migrated_engine)
    search_args = {
        "query_vector": [1.0, 0.0, 0.0],
        "top_k": 1,
        "filters": filters,
        "expected_profile": profile,
        "policy": AnnSearchPolicy(exact_fallback_on_underfill=False),
    }

    with pytest.raises(AnnIndexError, match="snapshot/profile"):
        repository.search_vector(
            **search_args,
            build=replace(build, snapshot_id="snapshot-ann-build-drift-other"),
        )
    with pytest.raises(AnnIndexError, match="snapshot/profile"):
        repository.search_vector(
            **search_args,
            build=replace(build, profile_id="0" * 64),
        )
    with pytest.raises(AnnIndexError, match="generation binding"):
        repository.search_vector(
            **search_args,
            build=replace(build, index_params_hash="f" * 64),
        )

    with migrated_engine.begin() as connection:
        connection.exec_driver_sql(f'DROP INDEX "{build.physical_index_name}"')
        connection.exec_driver_sql(
            f'CREATE INDEX "{build.physical_index_name}" ON chunk_embeddings '
            f"USING hnsw ((embedding::vector({profile.dimensions})) vector_ip_ops) "
            "WITH (m = 32, ef_construction = 64) "
            f"WHERE profile_id = '{profile.profile_id}' "
            f"AND embedding_dimension = {profile.dimensions}"
        )
    with pytest.raises(AnnIndexError, match="does not match"):
        repository.search_vector(**search_args, build=build)

    with migrated_engine.begin() as connection:
        connection.exec_driver_sql(f'DROP INDEX "{build.physical_index_name}"')
    with pytest.raises(AnnIndexError, match="missing physical index"):
        repository.search_vector(**search_args, build=build)


def test_dimension_above_hnsw_limit_is_rejected_before_ddl_but_exact_works(
    migrated_engine: Engine,
) -> None:
    dimensions = 2_001
    bundle, _ = _build_bundle(
        prefix="ann-high-dimension",
        scores=[1.0],
        dimensions=dimensions,
    )
    PostgresCorpusRepository(migrated_engine).import_bundle(bundle)
    profile = bundle.embedding_profile.to_identity()
    filters = RetrievalFilters(
        scope_id=bundle.snapshot.scope_id,
        snapshot_id=bundle.snapshot.snapshot_id,
        profile_id=profile.profile_id,
    )
    query = _unit_vector(1.0, dimensions=dimensions)

    exact = PostgresExactRetrievalRepository(migrated_engine).search_vector(
        query,
        top_k=1,
        filters=filters,
        expected_profile=profile,
    )
    assert len(exact) == 1
    assert exact[0].score == pytest.approx(1.0)

    with migrated_engine.connect() as connection:
        before = connection.scalar(
            text(
                "SELECT count(*) FROM pg_indexes "
                "WHERE schemaname = current_schema() "
                "AND indexname LIKE 'ix_ce_hnsw_ip_%'"
            )
        )
    with pytest.raises(AnnIndexUnsupportedError, match="at most 2000 dimensions"):
        PostgresHnswIndexManager(migrated_engine).ensure_index(
            filters=filters,
            expected_profile=profile,
        )
    with migrated_engine.connect() as connection:
        after = connection.scalar(
            text(
                "SELECT count(*) FROM pg_indexes "
                "WHERE schemaname = current_schema() "
                "AND indexname LIKE 'ix_ce_hnsw_ip_%'"
            )
        )
    assert after == before


def test_ann_build_receipts_enforce_identity_transitions_and_one_active_build(
    migrated_engine: Engine,
) -> None:
    _, _, profile, filters, first = _import_and_build(
        migrated_engine,
        prefix="ann-build-guards",
        scores=[0.9, 0.4, -0.2],
    )
    with pytest.raises(AnnIndexError, match="different HNSW specification"):
        PostgresHnswIndexManager(migrated_engine).ensure_index(
            filters=filters,
            expected_profile=profile,
            spec=HnswIndexSpec(m=24, ef_construction=64),
        )

    with pytest.raises(DBAPIError) as insert_error:
        with migrated_engine.begin() as connection:
            connection.execute(
                insert(index_builds).values(
                    build_id="ann-hnsw-" + "b" * 64,
                    snapshot_id=filters.snapshot_id,
                    profile_id=filters.profile_id,
                    index_params={"attempt": "bypass-building"},
                    index_params_hash="b" * 64,
                    status="active",
                    completed_at=func.now(),
                )
            )
    assert insert_error.value.orig.sqlstate == "55000"

    with pytest.raises(DBAPIError) as identity_error:
        with migrated_engine.begin() as connection:
            connection.execute(
                update(index_builds)
                .where(index_builds.c.build_id == first.build_id)
                .values(index_params_hash="0" * 64)
            )
    assert identity_error.value.orig.sqlstate == "55000"

    second_build_id = "ann-hnsw-" + "c" * 64
    with migrated_engine.begin() as connection:
        connection.execute(
            insert(index_builds).values(
                build_id=second_build_id,
                snapshot_id=filters.snapshot_id,
                profile_id=filters.profile_id,
                index_params={"attempt": "second-active-boundary"},
                index_params_hash="c" * 64,
                status="building",
            )
        )
        connection.execute(
            update(index_builds)
            .where(index_builds.c.build_id == second_build_id)
            .values(status="validated", completed_at=func.now())
        )

    with migrated_engine.begin() as connection:
        connection.execute(
            update(index_builds)
            .where(index_builds.c.build_id == first.build_id)
            .values(status="active")
        )
    with pytest.raises(IntegrityError) as uniqueness_error:
        with migrated_engine.begin() as connection:
            connection.execute(
                update(index_builds)
                .where(index_builds.c.build_id == second_build_id)
                .values(status="active")
            )
    assert uniqueness_error.value.orig.sqlstate == "23505"

    with pytest.raises(DBAPIError) as reverse_error:
        with migrated_engine.begin() as connection:
            connection.execute(
                update(index_builds)
                .where(index_builds.c.build_id == first.build_id)
                .values(status="validated")
            )
    assert reverse_error.value.orig.sqlstate == "55000"

    with pytest.raises(DBAPIError) as delete_error:
        with migrated_engine.begin() as connection:
            connection.execute(
                delete(index_builds).where(index_builds.c.build_id == first.build_id)
            )
    assert delete_error.value.orig.sqlstate == "55000"


def test_profile_generation_state_is_guarded_and_real_inserts_invalidate_ann(
    migrated_engine: Engine,
) -> None:
    bundle, _ = _build_bundle(
        prefix="ann-generation-guard-a",
        scores=[0.9, 0.3],
        profile_suffix="generation-guard",
    )
    repository = PostgresCorpusRepository(migrated_engine)
    repository.import_bundle(bundle)
    profile = bundle.embedding_profile.to_identity()
    filters = RetrievalFilters(
        scope_id=bundle.snapshot.scope_id,
        snapshot_id=bundle.snapshot.snapshot_id,
        profile_id=profile.profile_id,
    )
    build = PostgresHnswIndexManager(migrated_engine).ensure_index(
        filters=filters,
        expected_profile=profile,
    )

    with migrated_engine.connect() as connection:
        generation = dict(
            connection.execute(
                select(embedding_profile_generations).where(
                    embedding_profile_generations.c.profile_id == profile.profile_id
                )
            )
            .mappings()
            .one()
        )
    assert generation["embedding_count"] == build.profile_embedding_count == 2
    assert (
        generation["embedding_manifest_hash"] == build.profile_embedding_manifest_hash
    )
    assert generation["ann_physical_instance_id"] == build.physical_instance_id
    assert generation["ann_physical_index_name"] == build.physical_index_name
    assert generation["ann_index_params_hash"] == build.index_params_hash

    for values in (
        {"embedding_count": 1},
        {"embedding_count": 3},
        {"ann_physical_index_name": "ix_ce_hnsw_ip_" + "f" * 32},
    ):
        with pytest.raises(DBAPIError) as update_error:
            with migrated_engine.begin() as connection:
                connection.execute(
                    update(embedding_profile_generations)
                    .where(
                        embedding_profile_generations.c.profile_id == profile.profile_id
                    )
                    .values(**values)
                )
        assert update_error.value.orig.sqlstate == "55000"

    with pytest.raises(DBAPIError) as delete_generation_error:
        with migrated_engine.begin() as connection:
            connection.execute(
                delete(embedding_profile_generations).where(
                    embedding_profile_generations.c.profile_id == profile.profile_id
                )
            )
    assert delete_generation_error.value.orig.sqlstate == "55000"

    second_bundle, _ = _build_bundle(
        prefix="ann-generation-guard-b",
        scores=[0.7],
        profile_suffix="generation-guard",
    )
    repository.import_bundle(second_bundle)
    with migrated_engine.connect() as connection:
        invalidated = dict(
            connection.execute(
                select(embedding_profile_generations).where(
                    embedding_profile_generations.c.profile_id == profile.profile_id
                )
            )
            .mappings()
            .one()
        )
    assert invalidated["embedding_count"] == 3
    assert invalidated["embedding_manifest_hash"] is None
    assert invalidated["ann_physical_instance_id"] is None
    assert invalidated["ann_physical_index_name"] is None
    assert invalidated["ann_index_params_hash"] is None

    with pytest.raises(DBAPIError) as fake_binding_error:
        with migrated_engine.begin() as connection:
            connection.execute(
                update(embedding_profile_generations)
                .where(embedding_profile_generations.c.profile_id == profile.profile_id)
                .values(
                    embedding_manifest_hash="a" * 64,
                    ann_physical_instance_id="b" * 64,
                    ann_physical_index_name="ix_ce_hnsw_ip_" + "b" * 32,
                    ann_index_params_hash="c" * 64,
                )
            )
    assert fake_binding_error.value.orig.sqlstate == "55000"
